### PR TITLE
Custom Transport support.

### PR DESCRIPTION
**Pull request by kristinn**
More information about what can be achieved with a custom Transport
object can be found at https://godoc.org/net/http#Transport.

### CODE REVIEW

**Comment by kristinn** [comment]
I personally use this to be able to communicate with self signed HTTPS hosts in a dev environment.

**Comment by jmcvetta** [comment]
Seems like a good addition.   Please add test coverage for your new functionality, then I will be happy to merge the PR.  Thanks!

**Comment by kristinn** [comment]
Sure thing!

**Comment by kristinn** [comment]
I added a test for testing invalid TLS. First I make sure that we cannot connect without a custom transport and then I create a new request with a custom transport with the setting to allow invalid certs. The test case succeeds if that request succeeds.

This should be enough to actually test the custom transport. It's out of this PR's scope to actually test the transport functionality, that resides in the golang http package. :smile:

**Comment by jmcvetta** [comment]
Looks good - thanks for contributing!

**Comment by jmcvetta** [comment]
Released as [v3.1.0](https://github.com/jmcvetta/napping/releases/tag/v3.1.0).

**Pull request merged**
