### PR TITLE
Fix assert package for Nut.

### PR DESCRIPTION
**Pull request by jadengore**

### CODE REVIEW

**Comment by jmcvetta** [comment]
What is the purpose of this change?

**Comment by jadengore** [comment]
@jmcvetta My apologies, I meant to PR to my own fork.

The fix is for Nut, one of Go's dependency management system. The `bmizerany/assert` package contained in a few of your packages does not work with Nut. The software is three years old, and the pathing on one of the unit tests is making it unable for Nut to build the dependencies which is causing a fail. I've opened a PR for the issue here: bmizerany/assert#11, so hopefully you won't have to do a thing to get the fix in your source.

**Comment by jmcvetta** [comment]
@jadengore No apology necessary!  :)  

If your PR to the `assert` package is not accepted in a timely manner, please feel free to re-open this PR.  I don't personally use Nut, but I would still like Napping to be compatible with it.

**Comment by jadengore** [comment]
Thanks @jmcvetta! I really enjoy your Neoism package and currently using it on a project.

Also, another way we could make this work without my fork is by using a different assert package. [Testify](https://github.com/stretchr/testify) has a pretty good one, and it's well-updated. Maybe it would be better to switch your unit testing over to Testify!

**Comment by jadengore** [comment]
@jmcvetta I'm going to open a fix for each of these across a few of your packages, I don't think the PR will be merged any time soon.

**Comment by jmcvetta** [comment]
Feel free to port the assert statements to Testify.  I'll happily accept the PR!  Until now I didn't even notice it had been so long since `bmizerany/assert` was updated.

**Pull request closed without merging**
